# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "chore"
      prefix-development: "dev"
      include: "scope"
    labels:
      - "Scope: Dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "ci"
      prefix-development: "dev"
      include: "scope"
    labels:
      - "Scope: Dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
