name: Java CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: 'temurin'
          cache: 'maven'
      - name: Install packages
        run: |
          sudo apt-get install -y libgtk2.0-0 tesseract-ocr
      - name: Test
        run: mvn -B test -s .mvn/settings.xml
        env:
          MAVEN_TOKEN: ${{ secrets.GH_TOKEN }}
          MAVEN_USER: ${{ secrets.GIT_AUTHOR_NAME }}