name: Java Semantic Release

on:
  push:
    branches:
      - master
  workflow_call:

jobs:
  build-upload-release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-java@v4
      with:
        java-version: 16
    - name: Setup Node.js and semantic-release plugins
      uses: actions/setup-node@v4
      with:
        node-version: 16
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
    - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec semantic-release/git semantic-release/release-notes-generator
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: chmod +x ./.github/workflows/prepare-release.sh && npx semantic-release
